### ISSUE TITLE
Feature Request: export gtk-shell-shows-menubar

### ISSUE THREAD

**Issue by rilian-la-te** [lestcape/Global-AppMenu#1]
This GtkSettings variable must be set to TRUE for hiding a menu.

**Comment by lestcape** [comment]
Hi. Thanks for try to help, but see, i don't know what i'm doing here.

I don't like unity and also not mac os... So never have experience with the appmenu.

gtk-shell-shows-menubar don't have any effect here:
i set this without effect in :
```
     ~/.config/gtk-3.0/settings.ini
     ~/.config/gtk-2.0/settings.ini
      /etc/gtk-3.0/settings.ini
```

also without effect over the js code:
```
        let gtk_settings = Gtk.Settings.get_default();
        gtk_settings.set_property('gtk-shell-shows-menubar', true);
```

Thats also occurs actually:
    case 1: What is showed is the MenuBar, if i set on ~/.profile:
```
if [ -n "$GTK_MODULES" ]; then
  GTK_MODULES="$GTK_MODULES:unity-gtk-module"
else
  GTK_MODULES="unity-gtk-module"
fi

if [ -z "$UBUNTU_MENUPROXY" ]; then
  UBUNTU_MENUPROXY=1
fi
```
    case 2: What is showed is the App-Menu, if i set on my code:
```
        let env_gtk = GLib.getenv('GTK_MODULES');
        if(env_gtk) {
            if(env_gtk.indexOf("unity-gtk-module" ) == -1) {
                env_gtk += ":unity-gtk-module";
                GLib.setenv('GTK_MODULES', env_gtk, true);
                is_ready = false;
            }
        } else {
            env_gtk = "unity-gtk-module";
            GLib.setenv('GTK_MODULES', env_gtk, false);
            is_ready = false;
        }
        
        let env_ubu = GLib.getenv('UBUNTU_MENUPROXY');
        if(env_ubu != "1") {
            GLib.setenv('UBUNTU_MENUPROXY', "1", true);
            is_ready = false;
        }
```
    case 3: What is showed is the MenuBar, if i set on my code:
        https://github.com/linuxmint/cinnamon-session/pull/49/files

Anyway thanks.

**Comment by rilian-la-te** [comment]
Yes, your 1 and 2 cases (unity-gtk-module and UBUNTY-MENUPROXY) must also
be set. For reference see Unity-For-Arch repo (I do not remember actual
github address)

**Comment by lestcape** [comment]
Ok, but this is crazy, they have different dbus-path, different modules, differents environment variables and with the same code could show one or the another if the first is not available (in my case because the applet start is to late for set the environment). The windows on gnome shell or cinnamon are wrappers of the original ones, so they are not real and properties are not set on the real one if the wrapper not do this for you... So is common that some real configuration will not be apply to the cinnamon wrappers, thats is what i thing that occurs here, but i'm i can not be sure. I suppose that i need to do one thing and then the another, i will see if i found how remove the menubar.

Thanks.

**Comment by lestcape** [comment]
Apparently the problem is that muffin is not compatible and not take on account any of this, specially the unity Gtk settings. Force the settings to add this value will cause a problem on muffin and the application Gtk dies when you try to restart cinnamon. What unity-gtk-module does is first read for the environment variable UBUNTU_MENUPROXY if is true then apply some things one of then will be export the gtk menu, another will be connect to the signal "allocation change", for the menu bar. When the signal is capture they ask for the value gtk-shell-shows-menubar and if is true they set the height of menu bar to 1 and then move the menu bar one position down. This will cause the effect of not see the menu bar, the problem is that, muffin then try to adjust all windows and also with effects on idle that will cause a big problem. Apparently to fix this problem will be necessary add some code on muffin, and i think that cinnamon devs will not want to do this.

**Comment by rilian-la-te** [comment]
What are you mean about unity-gtk-module? Do you want do rewrite in on js, or use existing wit patches (it cannot run well outside of Ubuntu without patches)

**Comment by lestcape** [comment]
The unity-gtk-module or any other that i can use to remove the menubar is the same. Remove the menubar is not supported by Muffin. Apparently some recently changes in  Muffin also are the cause of the cinnamon freeze, the maximus extension (this extension do more less the same that i need) now not work. Also the unity patch for several application is restricted to the unity session.

**Comment by lestcape** [comment]
@rilian-la-te is impossible write a module on js, what you can do on js is intercept the windows before the construction and externally you could try to patch the windows using some gdk functionalities. How also muffin use this functionalities, this create a big miss, that need to be handled by muffin. For example, is you change some gdk-windows values, muffin need to have a signal to know that this happen and change internal his own properties, if this not occurs muffin continues thinking that windows is on one state and this is not true, so of course this will create freeze. The other way is that muffin provide a way to directly request to muffin a change, but this is more unreal, muffin only provide a little subset of properties and functionalities.

**Comment by lestcape** [comment]
@rilian-la-te can you tell me how recommend to the arch user your work on cinnamon spices?

Do you resolve the firefox problem?
Do you know how many importants applications are not currently working outsite unity?

Regards.

**Comment by rilian-la-te** [comment]
About spices: I does not know.
About firefox: I know how to resolve appmenu problem (I need to write CTypes applet), but I does not know about JS too much.
About applications: please post bugreports to me, I got all working except XUL and different user.

**Comment by lestcape** [comment]
1- An spice example.... http://cinnamon-spices.linuxmint.com/extensions/view/29

2- I send about to show and the problem is not resolved... https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/dbusMenu.js#L584

3- Evince is working?

**Comment by rilian-la-te** [comment]
About 3:
![screenshot from 2015-04-20 19-14-45](https://cloud.githubusercontent.com/assets/1329638/7230647/44dbe7c8-e789-11e4-83c8-0ee99ba7e812.png)
This is OK?
2. In Arch Firefox does not have Unity patches, we need an extension.
1. I know what is spices, I does not understand what you means in recommend package.

**Comment by lestcape** [comment]
4- Do you know that you can use regular expressions with the org.gtk.actions (the id) to show some standar icons? a simple lower case show some of them...
https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/dbusMenu.js#L726
https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/dbusMenu.js#L223
1- What i say is a short hint to install your packages on Arch. You have your package on some place?
How install it on arch?
2- Mmm... well... i will see...
3- No, is not ok, thats is the appmenu, not the menu bar.

**Comment by rilian-la-te** [comment]
1.Yes, I have my packages in AUR here: https://aur.archlinux.org/packages/?SeB=m&K=rilian (this is a complete list)
3. AFAIK, Evince does not have a menu (as for 3.16.1): https://github.com/GNOME/evince/blob/master/shell/evince-menus.ui does not shows any "menubar" entries.
Or you means that I should generate someone from Evince' s actions?

4. I like menus without icons. And native MenuModel applications (like file-roller) does not send icons to MenuModel.

**Comment by lestcape** [comment]
3- Evince have a patch on ubuntu to show the menu bar (and also another to export the menubar), The other is only for unity but not the first. I need to find a way to run evince as a unity session to export the menu.

1- Thanks for the reference to your packages.

4- You can give an option to show the icons or not as a user preference and show the gtk + kde or not show anything, but i don't like the unity mixed mode, where some menu items have an icons and another not...

**Comment by rilian-la-te** [comment]
3. Can you test my AppMenu under ubuntu/mint and tell me whether Evince is showing menubar? Sorry, I does not have Ubuntu right now.
4. Maybe, but it is not a priority for me.  But i wiill look for it. (I found some bugs in my dbusmenu.vala right now:))

**Comment by lestcape** [comment]
I think that will be more easy if you install ubuntu on a virtualbox, than if i install your packages, without know how and what will could occurs on unity, when i install it...

**Comment by rilian-la-te** [comment]
It will not work on Unity:) It is for xfce. Ok, I will try Ubuntu on vbox:)

**Comment by rilian-la-te** [comment]
Here I have a screen with Evince in VirtualBox Ubuntu:
![screenshot from 2015-04-25 22-50-00](https://cloud.githubusercontent.com/assets/1329638/7333766/16929622-eb95-11e4-8768-adcd1b16f688.png)

It is working OK, as far as I test. Will try firefox:)

**Comment by rilian-la-te** [comment]
Firefox also working out of box, but I does not test it fully yet. If you want, you now can build a Debian package for my plugin, I added debian folder for it.

**Comment by lestcape** [comment]
Ok, see evince:
![vlcsnap-2015-04-20-15h31m57s617](https://cloud.githubusercontent.com/assets/1389572/7383361/991f1912-ede3-11e4-823c-8c54968c5ccf.png)

**Comment by lestcape** [comment]
Firefox is working, just somehow after some time, he recovered the menu and on a layout update i get 0 items... apparently is because i need to call some about to show, or at less is what i can read here:
https://bugs.launchpad.net/plasma-widget-menubar/+bug/878165

**Comment by lestcape** [comment]
I lost several hours making test to fix firefox, without any result...When i take a rest i see that could be possible, that firefox will read the event of the register dbus iface to see if he is register, and after some time, if he don't received the signal, how he want, then possible he drop the menu and recover the control. 

I then try to find if this will be possible some how, i found that is necessary that he receive the response from the same source (the same connection), where he send the menu. Is possible that javascript (cinnamon) internally don't satisfy this requirement and then will be dropped the firefox menu.
Could you test if this assumption could be true in your implementation? Just is commented the code that emit the signal and see if the firefox menu will be dropped or not the menu after some time.

Thanks anyway for what you can do.

**Comment by Meiden-fc** [comment]
Did you take a look on this?

http://packages.ubuntu.com/search?keywords=firefox-globalmenu

I don't know if it's deprecated, but it used to be necessary for using the old global menu in GNOME 2.x.

**Comment by lestcape** [comment]
@Meiden-fc yes, will be really helpful know how the firefox-globalmenu packages is implemented on ubuntu to search for a compatible solution or at least find the cause of this. The problem is that i don't find the source code of this packages... Do you know where we can get a copy of this source? I can read and write code on several programing languages, so not matter the programming language.

**Comment by rilian-la-te** [comment]
The problem than firefox-globalmenu package is using entire firefox source
to build. I think, writing MenuModel exporter from scratch via js-ctypes
will be easier. Source of this outdated package is here:
https://launchpad.net/globalmenu-extension

**Comment by lestcape** [comment]
@rilian-la-te thanks, an old source could be more a distraction, than any other thing. Yes, will be more easy implement a different solution, that can be used on several distros, but if i want to do that on ubuntu (and i want) I suppose that also I need to understand how is implemented the current solution to avoid conflict with my new solution and this is more complex than only the fact that understand the official and fix my problem...
Is complex, i really don't see the way.

**Comment by lestcape** [comment]
I found the problem of firefox...
