### ISSUE TITLE
Add a main menu that allow use the application folder structure.

### ISSUE THREAD

**Issue by lestcape** [lestcape/Global-AppMenu#14]
This is an issue to discus about a new feature for the global menu.

There are some requests of cinnamon users, in the mint forum, for a menu that can show all folders of the apps in the menu structure. This is possible and "easy" to add right now inside the global menu. The global menu, do not display anything when we don't have any app selected. This is a fault, there are an available space that can be used to show the main menu or another type of menu, as the MAC OS that show what they considered a main menu. Of Course, without the application launcher (just as a setting menu). One possible option will be that, but why not satisfy the user request in an more integral menu?, This apparently is more as real GLOBAL one.

Then, as a primary idea the main menu could be displayed in this cases:
1- When not windows are selected.
2- When user click in the application icon or the application name, we can switching the main menu with the application menu.

To properly integrate this is required also provide more options, we not want affected users that only want the current feature and also user that only want the old menu style.

I'm open to speak about this for a while, if users think that will be good or an inconvenient. If not, this will be implemented as well, because currently i don't want the global menu, but maybe in this way, this will be a thing that i don't hate.

**Comment by Meiden-fc** [comment]
I think it is a very good idea. Go ahead!

**Comment by lestcape** [comment]
Not support for cinnamon anymore.
