### ISSUE TITLE
Seeing "Global Application Menu" tooltip when hovering on menu items

### ISSUE THREAD

**Issue by kminh** [lestcape/Global-AppMenu#17]
Hello, thank you for this useful applet.

Right now when I hover on the application's title or its menu I always see the "Global Application Menu" tooltip displayed. It is harmless but is quite annoying.

I'm using latest Cinnamon with Numix theme.

Any insight is appreciated.

**Comment by lestcape** [comment]
@kminh you are right... Maybe display the tooltip only when you are over the area of the application name or icon, but not over the menu itself?

**Comment by kminh** [comment]
Perhaps an option to disable it completely too? Or some kinds of delay before the tooltip is displayed.

**Comment by lestcape** [comment]
I'm not sure what you mean with delayed and i think will be worse if it's what i think... I don't like disabled it, because all cinnamon standar applet have a tooltip.

**Comment by lestcape** [comment]
I think is better now.

**Comment by kminh** [comment]
By delay I mean the applet should only display the tooltip when I keep hovering on it for a moment, e.g. 3 seconds.

Sure all standard applets have tooltips but only this particular applet requires a lot of hovering, and its tooltip is of no use as well.

**Comment by lestcape** [comment]
Can you test how is now? I think you will not need to hover your mouse over the icon or the application name commonly... So, i think the mayor problem is gone.

For delay the tooltip i need override the cinnamon behaviour.

Just test it. I also added keyboard navigation support.

I will add also verctor-box support: https://github.com/linuxmint/Cinnamon/issues/1775

**Comment by lestcape** [comment]
You can request in cinnamon website, an option to disable the tooltips, if you think is in general annoying. Global menu is not more annoying now than any other.
