### ISSUE TITLE
[Future Request] Jayatana integration

### ISSUE THREAD

**Issue by marco-murakami-movile** [lestcape/Global-AppMenu#19]
Right now it doesn't work with java applications. Could you integrate the jayatana library to display the java apps menu in your global menu? It would be nice to have it.

Thanks

**Comment by lestcape** [comment]
Hi, yes..
Can you help me?

1- Have you an example of any java application easy to install (low space) that you know is working on ubuntu?
2- Do you know any place where there are some specification (or code) for Jayanta?

The global menu have 4 parts right now. 
1- The KDE DBusMenu, was took from the gnome shell extension. 
2- The Gnome Dbus Menu, was implemented from an existing documentation.
3- The menu API, was took from the configurable menu applet.
4- The integration and all special cases, was making with a lot the help of several people as you can see in the readme.

I really have not idea of this, so any help will be appreciated.

**Comment by marco-murakami-movile** [comment]
Puedes instalar el JDK de java y una aplicación sería el monitor que trae por defecto. Para especificación de jayatana no he visto pero creo que también esta en launchpad. https://launchpad.net/~danjaredg/+archive/ubuntu/jayatanaa. Podemos ver el código fuente y ver que es lo que hace, aunque no creo que funcione mucho eso. Lo que se puede hacer es ver como lo integra Unity y ver las llamadas que hace a esa API.

**Comment by marco-murakami-movile** [comment]
Aquí está otro link en donde esta el source code: https://code.google.com/p/java-swing-ayatana/

**Comment by marco-murakami-movile** [comment]
Lo que no tengo idea es de cómo lo invoque Unity

**Comment by lestcape** [comment]
Ok, gracias.

Pude probrar, con policytool (una herramienta escrita en java del Jdk) que si se integra al global menu de unity, pero no a este.

Le escribí a los a jayanta en su gurpo de discución, a ver si me indican como proceder.
https://groups.google.com/forum/#!forum/java-swing-ayatana

La verdad no tengo ni idea de como se engranan las partes, y sería improbable que pueda hacer algo, si la forma de engranaje requiere código duro (C, C++). Yo solo uso java script así que bueno esperemos a ver que responden.

Saludos y gracias.

**Comment by lestcape** [comment]
Por lo menos ya tengo el código https://github.com/lestcape/java-swing-ayatana. Aparentemente, debería de ser cuestión de configuración, porque lo que hay es una una aplicación de c que hace de intermediaria entre java y quien exponga el servicio de menu global. La aplicación en c debería de comportarse como otra cualquiera y debería de funcionar de al menos llamarse al servicio que se crea cuando alguien habilita el applet.

**Comment by lestcape** [comment]
Puedes descargar la última versión de acá(https://github.com/lestcape/Global-AppMenu/archive/master.zip) con soporte para jayanta(https://github.com/lestcape/Global-AppMenu/commit/3557e482ca5d65ea9e9ba74c75bcbaaa0af4f3e3), sin embargo jayanta es algo lento, por lo que es posible que algunas aplicaciones necesiten añadir un tiempo de espera, para poder ser ejecutadas, cualquier problema reportalo, para que lo pueda arreglar.

Saludos.
