### ISSUE TITLE
Integration with Intellij Idea

### ISSUE THREAD

**Issue by felansu** [lestcape/Global-AppMenu#20]
This doesn't works with Intellij Idea menu.

**Comment by lestcape** [comment]
Yes i know, thanks. I also detected that this was going to be a problem when i began the global menu. You need to disable this feature, for now, i don't have a good idea of what i can do, if we speaking of expected behaviours. What you think will be?

**Comment by felansu** [comment]
No se como realizar esta integración, en casa utilizo Mint con Cinnamon, pero en el trabajo utilizo Ubuntu. En Ubuntu, el menú global si integra con Intellij Idea. 

Será que podemos ver como fue realizada dicha integración y aplicarla a tu proyecto ?

Gracias

**Comment by lestcape** [comment]
Me parece buena idea, lo que pasa es que no uso unity, así que ni idea de como está... Le tengo q

**Comment by marco-murakami-movile** [comment]
Hola Letscape!

Tengo entendido que hace uso de una libreria llamada Jayatana. Esta da la opción de migrar el menú en aplicaciones Java, como IntelliJ o NetBeans. Esto no pasa con Eclipse.

Quizá puedas ver que es lo que hace dicha librería e integrarla al código de tu applet. Al menos así es como lo soluciona Unity.

Espero sirva el comentario.

Lo he probado y hasta ahora esta excelente. Actualmente uso Ubuntu pero una vez que tu applet integre jayatana y funcione, migro a Mint.

Saludos y gracias por el applet!!!

**Comment by lestcape** [comment]
Ok, puedes probar si ahora se integra, luego de esto: https://github.com/lestcape/Global-AppMenu/commit/3557e482ca5d65ea9e9ba74c75bcbaaa0af4f3e3

**Comment by lestcape** [comment]
![captura de pantalla de 2015-09-16 19 53 01](https://cloud.githubusercontent.com/assets/1389572/9922346/dae82748-5cac-11e5-836d-cb9774ddc4a0.png)

**Comment by lestcape** [comment]
Aparentemente jayanta, devuelve nuevos identificadores de menú cada vez que se produce una actualización por lo que el menú se destruye completamente y luego se vuelve a crear, este proceso es lento y para evadir errores, es repetido varias veces en mi implementación. Por ejemplo acá https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/indicatorAppMenuWatcher.js#L340

comentando esta linea y la de arriba, se puede lograr más rapides, puesto que solo refrescaría una sola vez, pero trae problemas para otras aplicaciones como mint update... 

A ver si se me ocurre como mejorar esto sin que afecte a otros.

**Comment by lestcape** [comment]
https://groups.google.com/forum/#!topic/java-swing-ayatana/aURyeOPC_ZI
