### ISSUE TITLE
Unable to use with other IntelliJ IDE's

### ISSUE THREAD

**Issue by oliveiraev** [lestcape/Global-AppMenu#22]
Hi, nice work. Thank you.

Although #20 exists, it is discussed in Spanish and is related to IntelliJ IDEA and is partially resolved.

I'm using PyCharm. Already installed Jayatana and the swing menu correctly disappear, but, there is no menu item on the applet and ALT + <key> shorctuts doesn't work, making hard to even exit the application (at the momment, I need to do ALT + SPACE to summon the window menu and close there).

![captura de tela de 2015-09-29 17 19 57](https://cloud.githubusercontent.com/assets/320460/10177204/3af76104-66cf-11e5-8806-731df893467f.png)

Restarting Cinnamon (ALT + F2 then "r" then ENTER) closes the application.

 No log on glass.log :\ but I have some ```~/java_error_in_PYCHARM_0000.log```

**Edit**: I'm having issues uploading the dump here, so I made a pastebin: http://pastebin.com/XcTh42cT

**Comment by oliveiraev** [comment]
The same just happened with GParted and Synaptic. But with these I could try some blind ALT + KEY combinations until it triggers the menu (on the window).

I don't know if it helps on some way but, the [topmenu-applet](https://launchpad.net/~webupd8team/+archive/ubuntu/mate/+packages) needs ```GTK_MODULES=$GTK_MODULES:canberra-gtk-module:topmenu-gtk-module``` to work with synaptics, for instance.

**Comment by lestcape** [comment]
Hi, about jayanta, please execute the java application for terminal, and see what it`s the current problem:
https://www.youtube.com/watch?v=rIIMLlAeXTw&feature=youtu.be
https://groups.google.com/forum/#!topic/java-swing-ayatana/aURyeOPC_ZI

If you want a better integration, please add this to your environment variables manually to be loaded on session start:
export JAYATANA=1
export JAYATANA_FORCE=1
export JAVA_TOOL_OPTIONS=-javaagent:/usr/share/java/jayatanaa

About Gparted and synaptic, yes i will see this, i have not a good idea of what will be the best idea to resolve this. You can use now a custtom .desktop to launch the root applications without global menu support. There are others ways to no load the global menu for some specific application, but this need to be done for the root config not for the user (as synaptic... are run as root). 
http://askubuntu.com/questions/10481/how-do-i-enable-or-disable-the-global-application-menu
http://www.webupd8.org/2013/11/unity-global-menu-can-now-be-disabled.html

**Comment by lestcape** [comment]
See also this about jayanta: http://www.webupd8.org/2015/10/ubuntu-1510-and-1504-update-disables.html

**Comment by felansu** [comment]
Don't works:

![screenshot from 2015-10-09 22 41 49](https://cloud.githubusercontent.com/assets/1687697/10408559/fde2ccbc-6ed6-11e5-96f6-b1aa2ca7d579.png)

**Comment by lestcape** [comment]
@felansu download de applet from github and execute Intelligent in bash, create a launcher that call the app with a properly environment variable as I mention above. Apparently the launcher won't register the glib environment.

**Comment by felansu** [comment]
@lestcape i'm using shortcuts, my custom shortcuts are executing the command:
~/Software/idea-IU-141.2735.5/bin/idea.sh

This should be work ?

**Comment by lestcape** [comment]
@felansu There are some changes, aparently also involved ubuntu 14.04. I have not time to update my applet right now, so please open the file ~/Software/idea-IU-141.2735.5/bin/idea.sh and add this:
```
echo export JAYATANA=1
echo export JAYATANA_FORCE=1
echo export JAVA_TOOL_OPTIONS="-javaagent:/usr/share/java/jayatanaag.jar $JAVA_TOOL_OPTIONS"
```

after this lines:
```
#!/bin/sh
#
# ---------------------------------------------------------------------
# IntelliJ IDEA startup script.
# ---------------------------------------------------------------------
#
```

so your new beginning of the file will be:
```
#!/bin/sh
#
# ---------------------------------------------------------------------
# IntelliJ IDEA startup script.
# ---------------------------------------------------------------------
#

echo export JAYATANA=1
echo export JAYATANA_FORCE=1
echo export JAVA_TOOL_OPTIONS="-javaagent:/usr/share/java/jayatanaag.jar $JAVA_TOOL_OPTIONS"

message()
{
  TITLE="Cannot start IntelliJ IDEA"
  if [ -t 1 ]; then
    echo "ERROR: $TITLE\n$1"
  elif [ -n `which zenity` ]; then
    zenity --error --title="$TITLE" --text="$1"
  elif [ -n `which kdialog` ]; then
    kdialog --error --title "$TITLE" "$1"
  elif [ -n `which xmessage` ]; then
    xmessage -center "ERROR: $TITLE: $1"
  elif [ -n `which notify-send` ]; then
    notify-send "ERROR: $TITLE: $1"
  else
    echo "ERROR: $TITLE\n$1"
  fi
}
```


Probably, the menu will not shown correctly (jayanta is slow and the menu was informed too much time after the cinnamon global menu read the data). In this case, a cinnamon restart will show the menu.

I hope, this finally help.
Regards.

**Comment by lestcape** [comment]
@oliveiraev I think the best (more simple) way to prevent the ubuntu menu proxy when you run an application with high privileges , will be add this to your environment:
```
if [$UID == 0]; then
  UBUNTU_MENUPROXY=0
else
  UBUNTU_MENUPROXY=1
fi
```

**Comment by lestcape** [comment]
@oliveiraev i see you can do that:
1- sudo nano /etc/environment
2- Add this line to the file: UBUNTU_MENUPROXY=0
3- Save the file.

Then when you open a new application as root the menu will not be exported, but the non root application will export the menu. I want to know if i can set this automatically, but i think is not possible without ask for the root password.

**Comment by lestcape** [comment]
@felansu i update the description because there are another problem. See: https://youtrack.jetbrains.com/issue/IDEA-141725
![captura de pantalla de 2015-12-07 05 03 05](https://cloud.githubusercontent.com/assets/1389572/11625367/170b3a84-9ca0-11e5-9e09-37b2184851e4.png)

**Comment by felansu** [comment]
@lestcape thanks

**Comment by felansu** [comment]
Ok, i'm using ubuntu now... here intellij idea integration works fine :dancer:

**Comment by lestcape** [comment]
Thats good. I can not use the same way of unity to integrate the global menu, because the extension use javascript and clutter, not C and Qt. The difference is the performance and the possibility of use multiples threads.

**Comment by oliveiraev** [comment]
> @oliveiraev I think the best (more simple) way to prevent the ubuntu menu proxy when you run an application with high privileges , will be add this to your environment:
> 
> if [$UID == 0]; then
>   UBUNTU_MENUPROXY=0
> else
>   UBUNTU_MENUPROXY=1
> fi

Thanks for the feedback. I've stopped with Cinnamon until version 2.8

Just setting ```UBUNTU_MENUPROXY=0``` did the trick. thank you
