### ISSUE TITLE
global-appmenu doesn't work with latest cinnamon 2.8

### ISSUE THREAD

**Issue by xsitian** [lestcape/Global-AppMenu#24]
Dear developer, I really thanks for your hard work to bring us a globalmenu app for cinnamon desktop.
When I update the cinnamon desktop to latest 2.8, some applets are just missing including globalmenu applet, I guest it's linuxmint developer change some applet define or api, can you take a look and solve this? Thanks

**Comment by lestcape** [comment]
https://github.com/lestcape/Global-AppMenu/commit/759a5d1f1d624624a7c982a9bfa6eb294d973d3f
