### ISSUE TITLE
Plans on porting this to Gnome-Shell?

### ISSUE THREAD

**Issue by gentookid** [lestcape/Global-AppMenu#25]
Is it already possible/on the way/not planned to give support to Gnome3 users?
Provided they have unity-gtk-module [gtk,gtk3] ?

**Comment by lestcape** [comment]
This is not in my plan as i don't use Gnome Shell if it's what you want... In the opposite side, i need to say the applet can be migrated easy to the gnome shell if some one want to do that, except some specific parts that need to be overridden, because of  the specific cinnamon api.

**Comment by TamasBarta** [comment]
Hi @lestcape! I'm also in search of such extension for Gnome Shell. I'm also interested in porting it, however I'm not very experienced with creating extensions, and in general with programming on Linux desktop. So first I'll have to learn about it. Can you guide me to some documentations about how global menu works?

**Comment by lestcape** [comment]
@TamasBarta i have not a programming guide. As a reference, what i can say is that i overrride all the cinnamon PopupMenu api to be possible do a lot of things. There are more than 4000 line of code that i override. Specially you need to override the PopupMenuManager, that class is who not leave you to open at the same time several popupMenu. The reason of this restriction is just simplify the behaviour to be more easy control the popupmenu for normal shell applications. This also occurs in gnome shell of course. Basically, you need to take on account the Dbus api implementation of the canonical DbusMenu, that standard was created by KDE. Also you need the GTK DbusMenu, they are really different, so you need to find the type of your application (better say a type of the application that have your windows) and then use the corresponding DBus api for read the menu layout and properties. All menu have a windows association by the x-properties and the windows manager of your session need to have support for retrieve the DBus path and the sender id of an specific windows. In gnome shell you can have Wayland as a back-end also (and not X11), so is possible that can be more complex than that if you want support global menu over Wayland, additional to the X11 support.

In gnome shell there are not a directed way to get the xid of a windows inside javascript (gjs). You need to see how retrieved this value in a different way (will be of course slow, so you will see a degradation of the performance). To find how get the xid in gnome shell see the Maximus extension.

Additional you need to find how automatically enable the support  of the global menu.

Important reference:

The popupMenuAPI of global menu: https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/configurableMenus.js

The  PopupMenuManager: https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/configurableMenus.js#L1228

Canonical DBusMenu API: http://developer.ubuntu.com/api/devel/ubuntu-13.10/c/Dbusmenu-0.4.html
GTK DBusMenu API https://wiki.gnome.org/Projects/GLib/GApplication/DBusAPI

Important properties of a windows (in muffin windows manager, you need to find this for your windows manager):
https://github.com/linuxmint/muffin/blob/master/src/core/window.c#L335
https://github.com/linuxmint/muffin/blob/master/src/core/window.c#L344
https://github.com/linuxmint/muffin/blob/master/src/core/window.c#L347

A simple python implementation for read the DbusMenu API (KDE and GTK): https://github.com/RafaelBocquet/i3-hud-menu/blob/master/i3-hud-menu.py

Enabled the support of global menu: https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/indicatorAppMenuWatcher.js#L53

Explanation for devs (Maximus extension): http://mathematicalcoffee.blogspot.mx/2012/05/automatically-undecorate-maximised.html

Regards.

**Comment by lestcape** [comment]
Development skill required to make a global menu:

- JavaScript (expert)
- Dbus (expert). Is pretty hard, all things occurs over DBus.
- Specific Dbus Menu api KDE and GTK (expert).
- Gnome Shell API (expert). You need to know pretty well what you need to override and how to not create conflict with the standard implementation of the shell.

**Comment by TamasBarta** [comment]
That sounds a list of too much expert requirements... However I'm still really interested, so I'll start reading. I believe even if I achieve only parts of the full compatibility list, that's something, so I still want to start this happening on Gnome.

Thanks for your answer! It was really instructive!

**Comment by lestcape** [comment]
That's the idea I'm also not expert on all this things, i received a lot of help for people that also some of them are not expert. That's the good thing of linux.
Regards.

**Comment by lestcape** [comment]
Reopened: I'm on gnome shell now... Working in progress: https://github.com/lestcape/Classic-Gnome

**Comment by lestcape** [comment]
https://github.com/lestcape/Gnome-Global-AppMenu

**Comment by lestcape** [comment]
Was ported.
