### ISSUE TITLE
Search in GlobalMenu

### ISSUE THREAD

**Issue by jeremi360** [lestcape/Global-AppMenu#27]
Please add search box to search in Global Menu, like it have place in unity.
![](http://4.bp.blogspot.com/-lXqOuEWH-D0/T5ZhpRme06I/AAAAAAAAInk/i73WHrt7hFQ/s1600/ubuntu12.04-hud.png)

**Comment by lestcape** [comment]
Search is really crazy, and integrate it inside the applet is a thing to be thinking. First thing is find the location to be placed. Can not be possible like is in unity inside other different item because global menu is not a cinnamon feature. So certainly not inside the windows list.

**Comment by jeremi360** [comment]
I fun small program that provide this:
https://github.com/RafaelBocquet/i3-hud-menu

2015-12-06 10:59 GMT+01:00 Lester Carballo Pérez <notifications@github.com>:

**Comment by lestcape** [comment]
Yes in fact this is not the problem like i have the action inside a class (items), so i can easy filter the action by the name and only show the action that match with your search. The problem is how integrate this inside the desktop in a good way.

**Comment by alxgvr** [comment]
It doesn`t make any sense - search in global menu. Global menu - is just app menu. In Unity there in no search in MENU. You talk about DASH. It is a different thing.

**Comment by lestcape** [comment]
@alxgvr in the global menu implementation is where there are the interface to ask for the actions, so yes, the global menu have a way to execute actions and have a list of all actions, so, you can search in the global menu if you want and you know how (i known). The dash is just the client GUI in unity, so what is the problem then?

**Comment by lestcape** [comment]
Was implemented from Gnome Shell https://plus.google.com/+WorldofGnomeOrg
Cinnamon have not support any-more.
