### ISSUE TITLE
[Feature Request] Hide menu when not over and show appname online and other grafical customizations

### ISSUE THREAD

**Issue by SamuelePilleri** [lestcape/Global-AppMenu#29]
Hi,

I think it would be nice if the applet could show (maybe through settings) only the window title (app name) and reveal the menu only when `:hover`, pretty much like Unity. Removing the top bar when the app is maximized would be great, maybe moving the button for close/resize/minimize near the window name, again, just like Unity; this would help save some space on laptops and netbook, it would be great.

Finally, I would like to be able to customize the border under the chosen menu removing it, since I don't like that extra border.

I'm actually willing to help you with the code if necessary, but I've never done something like that before and I need some hints :wink: 

Thanks,
Samuele

**Comment by lestcape** [comment]
Hi, the hint is do not try to do that, because is not supported in cinnamon. You can remove the windows title out of the cinnamon process. Muffin will not let you handle the xprop of the windows directly from gdk inside cinnamon. I really don't know how in unity they merged the menu inside the windows, but it's a thing that clear is unrelated with cinnamon, javascript or the global menu. Is a different feature, in my opinion an unnecessary invention. I like more the feature of hide the menu when you not need.

**Comment by SamuelePilleri** [comment]
Hi, thanks for your reply.

I was actually wondering if they might have faked it in some way, like playing with "`z-index`es" and making the windows title behind the topbar.

Actually, I've noticed that you can get a similar behaviour by killing the window decorator process, but, of course, this would remove the frame to all windows, not just the one you want. No idea if this can be done runtime to a single window.

By the way, thanks for your awsome work, keep pushing, and happy new year!
Samuele

**Comment by SamuelePilleri** [comment]
While Googling around I found that it's actually possible to remove the decorations to a window, and there's a Cinnamon plugin that does exactly that! The plugin is [Cinnamon Maximus](http://cinnamon-spices.linuxmint.com/extensions/view/29) and is tested with Cinnamon 2.8. The source code is pretty short (just one file), but the license is not specified.

Are you interested in bringing this feature? Do you like it?

**Comment by lestcape** [comment]
@SamuelePilleri yes, please see: https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/WindowProperties.js

You can find the Maximus code inside the global menu, I'm not happy with the performance of this feature and the number of bugs that we can get, so is disable and really i don't use this code.

I will repeat you the same, to get this behavior, what occurs is that: The code execute the process of   decoration-undecoration a windows outside cinnamon. This is hard, buggy and slow.

Happy new year.
Regrads.

**Comment by lestcape** [comment]
I think you need to see that: https://github.com/linuxmint/muffin/issues/183

**Comment by lestcape** [comment]
About the other options, well, i was thinking that they was working, but i realized that i not connect the "open on hover" option to the main menu, it's just for the secondary menu, i will connected the open "on hover signal" to the main menu.

**Comment by lestcape** [comment]
If what you want is that the menu work as unity, forget it or create your own branch. I will not hide the menu or the icon or the label automatically like unity, this have not sense to me without change all behaviours, to the unity way. This only can complicate the code and will be annoying, flashing things inside the desktop.

Please see:
https://bugs.launchpad.net/ubuntu/+source/unity/+bug/783240

**Comment by SamuelePilleri** [comment]
I see. I was considering forking your code, but I have to get a better knowledge of Cinnamon before. Moreover, if you're saying the features I'd like to implement are slow and buggy, I might move to another DE.

Happy new year!

Regards,
Samuele

**Comment by lestcape** [comment]
Not support for cinnamon any-more.
