### ISSUE TITLE
  Visual effects are laggy with new Linux Mint 17.3 (Cinnamon 2.8.6)

### ISSUE THREAD

**Issue by tradespite** [lestcape/Global-AppMenu#30]
After upgrading from Mint 17.2 to Mint 17.3 by starting an application (especially nemo) sometimes (not always) the visual effect, which opens the window, is buggy/laggy.
It also happens when I switch between the applications, but again only sometimes.

After disableing the Global Application Menu all visual effects work smooth again.
So I assume this Applet has a bug with new Linux Mint 17.3

Maybe someone else can verify this issue.

**Comment by lestcape** [comment]
Hi. In cinnamon, the components (clutter actors) will not be render directly inside a GL context, they will be rendered after you display it. So, when the components will be displayed, is the time to also render his representation inside GL. This mean a lag to perform this task. If you join this fact with the visual effect, then you really can note that. There are some buggy applications that not remember the id of his menu items as jayatana, this duplicate the process, to then be possible handle this type of applications. Maybe this is why you see the lags now and not before. It's pretty difficult optimized the global menu in this context. Anyway yes, i will try to optimized as possible.

**Comment by lestcape** [comment]
Yes they are laggy, i'm moving the applet to gnome shell. This applet have not support for cinnamon.
