### ISSUE TITLE
How to use it with GNOME 3?

### ISSUE THREAD

**Issue by artemjackson** [lestcape/Global-AppMenu#31]
How to use this extension with GNOME 3.18 ?

**Comment by lestcape** [comment]
I suppose you say gnome shell 3.18, if is the case, you need to port the applet to a gnome-shell extension. https://github.com/lestcape/Global-AppMenu/issues/25

**Comment by artemjackson** [comment]
Thenks! Would be great if someone made it

**Comment by lestcape** [comment]
Reopened: I'm on gnome shell now... Working in progress: https://github.com/lestcape/Classic-Gnome

**Comment by jmaris** [comment]
hey, any progress on this ? :) it'd be awesome to have a globalmenu in gnome shell :)

**Comment by lestcape** [comment]
Not, will not be any progress... The idea it's not port the global menu to gnome shell, the idea it's port the global menu to work inside a gnome shell extension. This gnome shell extension it's an extension that migrate the whole cinnamon desktop features to gnome shell... Witch some changes of course... When this extension  will be finished i will make it run inside the extension. But port a whole desktop to run inside another it's not a thing of 3 days. Again the works occurs here: https://github.com/lestcape/Classic-Gnome and not here.

**Comment by lestcape** [comment]
https://github.com/lestcape/Gnome-Global-AppMenu

**Comment by lestcape** [comment]
Was ported.
