### ISSUE TITLE
Horizontal black-ish lines on top and bottom of menu

### ISSUE THREAD

**Issue by stunito0o0o0** [lestcape/Global-AppMenu#34]
Hello,
first I want to say that this is an awesome applet, but when I put a light theme for my panel(it's on top of the screen) I see those black-ish lines on top and bottom of the menu and it's really annoying. Not sure if this is a bug, or a design decision, but in case its intentional I want to ask you for a setting to turn it on and off in the configuration menu of the applet.
P.S. I am using Macbuntu 16.04 transformation pack and I am using "MacBuntu-OS-UCGM" for the desktop theme.
Thanks :)

**Comment by lestcape** [comment]
I don't know what version you have. The github version, have several problems, no only this problems. The Spices version only work on cinnamon 2.6, not in 2.8 or 3.0...

There are a setting option to show or not the separators.
![captura de pantalla de 2016-08-15 10 49 47](https://cloud.githubusercontent.com/assets/1389572/17670298/f301312c-62d6-11e6-9cf5-273ff37bc0e2.png)

This is a design decision, because  there are some menu layouts that used this separators. The style of the separators are decided by the theme not by configurable Menu.

**Comment by lestcape** [comment]
Ahhh... sorry, you speak about the Global Menu.... Yes there always incompatibilities with the theme, i only can warranty a good match with the standard cinnamon theme, others themes need the be fixed to properly support global menu. As Global menu it's a third party applet this is if the theme author want to do that. I can try be more compatible with more themes, but this is not the way...

**Comment by stunito0o0o0** [comment]
Hello,
Thank you for quick response. I tried to look at your code, but I am not
really good at programing and I couldn't find how to fix the problem. Maybe
if you can tell me what I can change to make the lines transparent, or
atleast the same color as the panel. Thanks again!

На 15.08.2016 г. 19:56 "Lester Carballo Pérez" <notifications@github.com>
написа:

**Comment by lestcape** [comment]
Can you take an screen shoot and share with me the problem, that you notice?

**Comment by stunito0o0o0** [comment]
Yes of course, like i said I am using a MacBuntu theme. I am attaching 2 screenshots - the menu itself with the lines and my themes and applet settings.
![menu](https://cloud.githubusercontent.com/assets/21028278/17713055/a1657a40-6401-11e6-9c08-dcb27729a0f2.png)
![settings](https://cloud.githubusercontent.com/assets/21028278/17713056/a17b293a-6401-11e6-8a07-ff53ae593dcf.png)

**Comment by lestcape** [comment]
Thanks.

This is where I set the related style class:

https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/configurableMenus.js#L5751
https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/configurableMenus.js#L5772
https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/configurableMenus.js#L5773

You can remove or commented (//) this lines to see the style that is the cause of the lines.
Example:

```
    this.launcher.actor.add(this.actor);
    //this.actor.set_style_class_name('applet-container-box');
    this.actor.connect('notify::mapped', Lang.bind(this, this._onMapped));
```

**Comment by stunito0o0o0** [comment]
Okay, I didn't quite get what you are telling me to do, BUT i thought of something else. It's a noob solution, but it works lol. So what i did was I took a screenshot and opened it in GIMP. Then i chose the  "color picker tool" and selected the green-ish line of the menu. The hex color was "#326b65" so i looked for it in the "cinnamon.css" file of the theme (/usr/share/themes/MacBuntu-OS-UCGM/cinnamon/cinnamon.css). I found some css style for "popup-sub-menu" and there was a border argument(if that is what it is called anyway) with the color i was searching. So I commented it (I attached a screenshot below) and now the lines are gone. I checked the "troubleshoot menu" of cinnamon and it is still the same color so I guess it is not the same color as the borders color. Since I'm at the css file i looked for the notifications buble background(it was a .svg file) and it is the only black thing in the whole theme, so i changed it to white with GIMP. In case someone needs it in the future I am attaching a screenshot of the change i made on the css file and a zip of the theme(with changed notifications buble color and comented border)
![screenshot from 2016-08-17 00-33-00](https://cloud.githubusercontent.com/assets/21028278/17717062/6ac30de6-6414-11e6-948c-1ff1ddbe0a8a.png)
[MacBuntu-OS-UCGM.zip](https://github.com/lestcape/Global-AppMenu/files/421391/MacBuntu-OS-UCGM.zip)

. 
I want to thank  you again for the great applet, and for the quick response and great patience to a newbie like me.

**Comment by lestcape** [comment]
:-) I'll try to fix the problem when I get home. I think the  popup-sub-menu style is not needed, so can be removed from the actor in this case, but i need to try first. In that way, you will not need to remove the style.

What you are doing, the style modifying, have side effects in others places of cinnamon.

**Comment by stunito0o0o0** [comment]
Yea I guess, it does, but it's just a border for something, so no rush :)

**Comment by lestcape** [comment]
Don't be modest, you found the source of the problem. I appreciate your help and the least I can do is repay it in this way: https://github.com/lestcape/Global-AppMenu/commit/8a54ed6fb1dff50d0e9ff057fcda654f9a9ba183
