### ISSUE TITLE
Make font less bold

### ISSUE THREAD

**Issue by alxgvr** [lestcape/Global-AppMenu#35]
Hi. I would like to ask to make font less bold, or increase space between main menu items (horizontaly).

**Comment by lestcape** [comment]
I will not want to create any hard-code theme modification for this applet. If some people are interesting on give support for the global menu in his theme, he need to speak with me... I have not problem to help and i can provide all selectors that he want, to modify the aspect of the applet. The global menu it's not interesting to me, I don't use it...
