### ISSUE TITLE
Doesn't work with Cinnamon 3.0.7

### ISSUE THREAD

**Issue by Aceler** [lestcape/Global-AppMenu#41]
Looking glass says:
`error t=2016-11-05T00:41:05Z second argument to Lang.bind() must be a function, not undefined
error t=2016-11-05T00:41:05Z [Applet "globalAppMenu@lestcape"]: Failed to load applet: globalAppMenu@lestcape/21
error t=2016-11-05T00:41:05Z Could not load applet globalAppMenu@lestcape
info t=2016-11-05T00:41:05Z Adding systray: thunderbird (24x24px)
info t=2016-11-05T00:41:05Z Hiding systray: banshee
info t=2016-11-05T00:41:05Z Adding systray: mintupdate.py (24x24px)
info t=2016-11-05T00:41:05Z Indicator AppMenu Whatcher: Acquired name com.canonical.AppMenu.Registrar
info t=2016-11-05T00:41:05Z Indicator AppMenu Whatcher: RegisterWindow 58720276 :1.33 /MenuBar/1
info t=2016-11-05T00:41:05Z Indicator AppMenu Whatcher: RegisterWindow 46137513 :1.29 /com/canonical/menu/2C000A9
info t=2016-11-05T00:41:05Z Indicator AppMenu Whatcher: RegisterWindow 85983267 :1.79 /com/canonical/menu/5200023
info t=2016-11-05T00:41:05Z Indicator AppMenu Whatcher: UnregisterWindow 88080391
info t=2016-11-05T00:41:05Z Indicator AppMenu Whatcher: UnregisterWindow 85983267
info t=2016-11-05T00:41:05Z Indicator AppMenu Whatcher: UnregisterWindow 58720276
info t=2016-11-05T00:41:05Z Indicator AppMenu Whatcher: UnregisterWindow 46137513
error t=2016-11-05T00:41:05Z applet._extension is undefined
error t=2016-11-05T00:41:05Z Failed to refresh list of applets`

.xerrors was more spectific:

`(cinnamon:2081): Cjs-WARNING **: JS ERROR: TypeError: invalid 'in' operand this._registeredWindows
IndicatorAppMenuWatcher.prototype._getMenuClient@/home/aceler/.local/share/cinnamon/applets/globalAppMenu@lestcape/indicatorAppMenuWatcher.js:410
IndicatorAppMenuWatcher.prototype._tryToGetMenuClient/<@/home/aceler/.local/share/cinnamon/applets/globalAppMenu@lestcape/indicatorAppMenuWatcher.js:658
`

**Comment by lestcape** [comment]
You are using the last version, i update the code to support cinnamon 3.0.7, 3 days ago.

**Comment by Aceler** [comment]
Yes! That's why I hoped it will work.

Just gitcloned it again, to be sure, but the output is the same.

**Comment by lestcape** [comment]
The problem it's the lot of changes that was introduced in cinnamon 3.0.7, i will try to update again cinnamon tonight and see again if the problem appear to me, but for me in a recently state of cinnamon 3.0.7 it's working.

**Comment by lestcape** [comment]
I really can not reproduce your error after install the latest version of cinnamon. Anyway i need to change something to support JAyantana and enhanced the performance, so probably after the change this will work for you, but i don't know. If i can not reproduce the problem i can not fix it.

**Comment by Aceler** [comment]
I see. But I have the same problem on desktop and on laptop, so it is not just a random glitch.

It works in VirtualBox, so I think it conflicts with something. Applet, maybe, or app. I'll investigate this.

**Comment by lestcape** [comment]
Probably, the conflict it's because of an specific application that you don't have in virtual box and i also I have not, but it's installed in your desktop and laptop.

**Comment by Meiden-fc** [comment]
I'm having the same issue after I had updated the applet to the latest build.

**Comment by Aceler** [comment]
I found out a difference between my virtualbox setup and a real hardware setup. The difference is, that I set up VirtualBox on 31 of october, so it have previous version of the applet. The previous version from 31 of october works fine.

**Comment by lestcape** [comment]
The previous version, won' t work on cinnamon 3.2, and cinnamon 3.2 it's out. I don't never say that this not occurs, just i need to know how i can reproduced that, to try to fix it. If i can not reproduce the problem, i can not fix it.

**Comment by lestcape** [comment]
The error that prevent to load the applet it's:
error t=2016-11-05T00:41:05Z second argument to Lang.bind() must be a function, not undefined error t=2016-11-05T00:41:05Z [Applet "globalAppMenu@lestcape"]: Failed to load applet: globalAppMenu@lestcape/21 error t=2016-11-05T00:41:05Z Could not load applet globalAppMenu@lestcape info t=2016-11-05T00:41:05Z 

The error in .xsession-errors don' t say anything about the cause of this error. Will help to know the the function that it's not localized. Normally this is output to .xsession-errors

**Comment by Aceler** [comment]
I don't understand, current version of cinnamon in Mint 18 stable is 3.0.7. I should wait for Mint 18.1 to upgrade cinnamon to 3.2?

**Comment by lestcape** [comment]
Cinnamon is a desktop, Mint is a distro. The desktop it's in version 3.2, and you can install the desktop from source if you want, in the moment that you want. If you don't want to install the desktop from source, you can find if there are a repository of cinnamon, and install the desktop from this repository.

Remember that cinnamon it's not specific of Mint... For example i have cinnamon in ubuntu. This now apparently it's a problem with an incompatibility with the current version of cinnamon hat all Mint user have, i can support an specific version of Mint, but i don't development any thing focus on Mint, i don't use Mint.

**Comment by tashimotor** [comment]
same here, doesnt work.
mint 18, cinnamin 3.0.7
[log](http://pastebin.com/eXxq9jsA)

**Comment by Aceler** [comment]
So, we just need to use previous version with cinnamon 3.0.7 and a newest version with newest cinnamon, right :-)

**Comment by Meiden-fc** [comment]
Can you share the previous version? I deleted it already.

**Comment by Aceler** [comment]
Use Git, Luke :-)

https://yadi.sk/d/AvG4wdJayL2wj

**Comment by Meiden-fc** [comment]
Thank you mate! I rarely use git, so when I need something I just click the "download" button in the website :D

PS: It worked flawlessly.

**Comment by Meiden-fc** [comment]
@lestcape I'm using Cinnamon in Ubuntu either, and I was having the issue as well. It is Cinnamon 3.0.7 and the applet crashed just after had updated it.

I could make it work again with the version that Aceler shared two messages above.

**Comment by lestcape** [comment]
Let me try to install mint and reproduce the problem and see if i can do some thing this week end. In any case, i can revert the changes, save a release and then merge the changes again.

@Meiden-fc yes, but this is apparently a problem of the cinnamon version, not distro relate. 

In cinnamon 3.2 was removed the box pointer, was added the vertical panels, and all cinnamon internal api was changed to support this new features. So, to compensate that, i remove the reference to the cinnamon API as it's unstable (i can not support several different APIs at the same time). I suppose that there are some references to cinnamon API yet, that i don't remove and this is the cause of the problem.

**Comment by lestcape** [comment]
The confusion it's because cinnamon jump from version 3.0.7 to 3.2, so there are a lot of missing  tagged versions between this two versions. A lot of changes in the middle and there are no way to reference changes by versions... cinnamon 3.0.7 it's then several different code...

Please see cinnamon releases: https://github.com/linuxmint/Cinnamon/releases

**Comment by lestcape** [comment]
This was fixed here: https://github.com/lestcape/Global-AppMenu/commit/294671fec415bbf637295f877d4766e9beaec070

There are some update planed to also fix more bugs (as JAyantana)...
