### ISSUE TITLE
Lengthening the max characters of application name doesn't work

### ISSUE THREAD

**Issue by viggy96** [lestcape/Global-AppMenu#43]
Changing the max length of focused application name doesn't do anything. Its still too short, I want it to show most of the title of the application I have open, but it doesn't.

**Comment by lestcape** [comment]
This is a normal criteria in cinnamon, application are cut off always. In cinnamon windows list, in cinnamon menu applet or whatever... This for a reason... If will resolved that in cinnamon applets you can write some line about it here and i will open the issue again.
