### ISSUE TITLE
Disable Gradient

### ISSUE THREAD

**Issue by jchamb2010** [lestcape/Global-AppMenu#44]
Hello,

I would like to be able to disable the gradient that is applied to the title of the running application ("Google Chrome" for example). I took a look through the source code and commented out all instances of LinearGradient but that didn't seem to have any effect when I reloaded Cinnamon.

I personally do not like the fading name and it "hiding" behind the menus. I would like it to have the full name, followed by the menu if possible.

Thank you for any help.
John C.

**Comment by lestcape** [comment]
https://github.com/lestcape/Global-AppMenu/issues/43
https://github.com/lestcape/Global-AppMenu/issues/10
