### ISSUE TITLE
Unstyled application name

### ISSUE THREAD

**Issue by oliveiraev** [lestcape/Global-AppMenu#48]
Possibly related with #33 

Tried to checkout commit by commit as I've done with #33 but no luck.

I agree that the result with 'Cinnamon' theme is quite acceptable but, again, other 'official' themes also have some visual differences between application name and the menu itself.

On 'Linux Mint' theme, Application name is not aligned with menu...

![image](https://cloud.githubusercontent.com/assets/320460/22588578/9a2d9f2e-e9ed-11e6-9552-6de8c6d07137.png)

Mint-X variants completely mismatches...

![image](https://cloud.githubusercontent.com/assets/320460/22588609/bf9c633a-e9ed-11e6-8d48-31fe23b0807a.png)

windowTitleApplet@rymate1234 does the job correctly. But It isn't live/online (yes, I know about Cinnamon limitations) and misses the cool feature of fade at n<sup><small>th</small></sup> character - which is the reason of this issue.

![image](https://cloud.githubusercontent.com/assets/320460/22589001/5e1d1e5e-e9ef-11e6-91e3-444397314099.png)

Altough being so simple, I couldn't port windowTitleApplet@rymate1234 to make a PR. I don't know what actor I should modify.

If you *really*  believe it's a theme issue (even existing compatible extensions), please, tell me the missing classes and styles and I'll make some tests and pull requests.

Thank you for attention and thank again for the awesome job on this applet. :1st_place_medal:

**Comment by lestcape** [comment]
@oliveiraev I will not support cinnamon any more... I'm on gnome shell now and working in this project:

I will port all my work to my own project:
https://github.com/lestcape/Classic-Gnome
