### ISSUE TITLE
MonoDevelop not woring 

### ISSUE THREAD

**Issue by enep** [lestcape/Global-AppMenu#49]
Hello, the global menu in the "MonoDevelop" application does not work

**Comment by lestcape** [comment]
Hi, this implementation it's a client api for an standard KDE DBusMenu API, Gtk 3 API and also the Connonical Menu.Registrar API. So, this implementation have not any hack for an specific application and do not resolve any individual problem. Also, this is a gjs/cjs implementation (an implementation in a javascript language), so, it's impossible create a hack in a javascript languages. If some specific applications can not be integrated, this mean the application have not the support to be integrate.

Also if you used an additional tools (https://github.com/kekekeks/monodevelop-appmenu) and the tools will not export the menu in one of this variants or do not export the menu in a good way, this is not concidered a fault of this global menu implementation, it's a fault of the client application...
