### ISSUE TITLE
Not work on linuxmint 18.2

### ISSUE THREAD

**Issue by tarasenko** [lestcape/Global-AppMenu#51]
error t=2017-06-07T19:59:43.006Z [Applet "globalAppMenu@lestcape"]: Error importing applet.js from globalAppMenu@lestcape
error t=2017-06-07T19:59:43.006Z Could not load applet globalAppMenu@lestcape

**Comment by lestcape** [comment]
Read the description and also:
https://github.com/lestcape/Global-AppMenu/issues/50
