### ISSUE TITLE
not working in Linux Mint 18.2

### ISSUE THREAD

**Issue by cheenu2** [lestcape/Global-AppMenu#53]
My first time trying to use this applet.

In fresh install on Linux Mint 18.2, I installed applet per
http://www.omgubuntu.co.uk/2016/10/global-menu-applet-linux-mint-cinnamon

Cinnamon LookingGlass log error
error t=2017-07-25T15:21:14.213Z [Applet "globalAppMenu@lestcape"]: Error importing applet.js from globalAppMenu@lestcape
error t=2017-07-25T15:21:14.214Z Could not load applet globalAppMenu@lestcape

**Comment by lestcape** [comment]
https://github.com/lestcape/Global-AppMenu/issues/50

**Comment by cheenu2** [comment]
Thanks - sorry to see all the people problems around Cinnamon.
Is there any desktop that includes/supports this Global-AppMenu (outside of unity).

**Comment by lestcape** [comment]
I port this implementation to gnome shell... Mate and xcfe have support thanks to vala panel appmenu:
https://github.com/rilian-la-te/vala-panel-appmenu

Kde have support for qt application only...
