### ISSUE TITLE
Ugly icons on menu even with the option unchecked

### ISSUE THREAD

**Issue by Meiden-fc** [lestcape/Global-AppMenu#6]
Noticed on gedit and system monitor.
![seleccion_049](https://cloud.githubusercontent.com/assets/8806527/7698764/12e50844-fe13-11e4-8fd9-357af7e06ef4.png)

**Comment by lestcape** [comment]
Yes thats true, i need to add support to override the current style with a more specific one. The option of icons are only for menu item that are not a submenu. Thats is a real problem currently.

**Comment by Meiden-fc** [comment]
I don't want to open another issue for this: It seems it doesn't work with Nemo.

**Comment by lestcape** [comment]
Nemo tiene una característica (accesible en el menú) para mostrar o no mostrar la barra de menu. Si cuando nemo inicia esta característica no está habilitada (habilitada por defecto), es imposible que se consiga mostrar el menú y al cambiarla, no me entero, puesto que no tengo el menu, no fue exportado. Por otra parte si cinnamon settings establece el modulo "unity-gtk-module", después de iniciar nemo, entonces nemo no podrá contener esta caracteristica. Nemo arraca antes que todos los programas, muy rápido, por lo que es el más problemático de todos, pero hasta ahora no me a dado ningun problema. Reviza lo que dices y fijate a ver si puede hacer que nemo arranque por defecto con barra de menu activa. Esto debe de funcionar, y si no funciona la verdad no se que decirte, porque aparentemente tienes algo diferente al resto de los mortales en tu configuración.

**Comment by Meiden-fc** [comment]
Tienes razón Lester, el problema venía al activar el menú pulsando ALT, lo cual lo hace visible temporalmente. La solución pasaba por marcar la opción "Barra de menú" desde el menú "Ver".

Muchas gracias :D

**Comment by lestcape** [comment]
https://github.com/lestcape/Global-AppMenu/commit/91ff0def2a15707dc7c39addfd536957ac3a54c8
