### ISSUE TITLE
allow the applet to show up on multiple (panels,) monitors

### ISSUE THREAD

**Issue by hendricha** [lestcape/Global-AppMenu#7]
Cinnamon 2.6 let's the user copy applet configuration from one panel to another, and let's the user have multiple panels on multiple monitors. This applet currently does not support this feature. My use case is simple, let me have the global menu on both of my monitors (so on different panels.)

**Comment by lestcape** [comment]
I don't understand what you say. If what you want is move the applet to other monitor/panel, this is currently possible. If what you want is have several instances of the applet, well... You really will not want this when you see the result. The menu is genereted dynamically (on fly as soon as the app appears) is pretty hard for cinnamon handled that, as the compositor thread is ocupate for a while on this task (this can see when you open a video) This is without take into account that the applet contain a unique session service and as i'm not a developer of cinnamon, this service can not be shared easy with several client, thats mean that i need hack the cinnamon main class injecting the functionality to be accessible for all instance.

This is a beta project and i don't like the global menu, so i'm not agree on make the thing more complicated. Feel free to create what you want and test if is factible, i also can help you in that case and also if you will maintain the applet i have not problem with it. Regards.

**Comment by lestcape** [comment]
After analyse a little i see there are a partially solution, and is share the cinnamon menu structure with all instance hacking the main class of cinnamon, and only show the menu on one instance over the monitor where the windows is, but for be possible do that, cinnamon need to create a solution for allow only create one instance of an applet per monitor and this is not possible currently. I see @mtwebster speaking of some similar problem for find a better solution in cinnamon windows list. So, is possible, that this will be implemented in the future.

**Comment by lestcape** [comment]
Not support for cinnamon anymore
