### ISSUE TITLE
Menu disappears in LibreOffice Writer

### ISSUE THREAD

**Issue by Meiden-fc** [lestcape/Global-AppMenu#9]
I've noticed that globalmenu disappeared after the first time that I opened LO Writer.

He notado que el menú desaparece después del primer inicio de LO Writer tras haber añadido el applet al panel

**Comment by lestcape** [comment]
No te entendí... De todas formas ando complicado con tramites de doctorado, y no voy a poder hacer mucho en unos 15 días. A mi no me sucede nada con libre office. Está funcionando bien. Que versión tines? La última de acá?

**Comment by Meiden-fc** [comment]
Tengo 4.4.3.

El asunto es que globalmenu funcionó la primera que abrí Writer. Después de eso no ha vuelto ha funcionar, no aparece ningún menú, ni en el panel ni en la propia aplicación.

Consigo hacerlo funcionar si elimino el applet del panel, y lo añado otra vez mientras tengo Writer abierto.

Un saludo, ¡y ánimo con ese doctorado!

**Comment by lestcape** [comment]
Si, tienes razón, como yo no uso esto lo pongo para ver que pasa y siempre funciona...

A ver que le hago despues.

**Comment by lestcape** [comment]
Fíjate a ver si está resuelto, pero creo que solo parcialmente. Es probable que en algunas algunas veces necesites cambiar a algún otro menú de otra ventana (o al escritorio), para poder ver el menú. No debe ocurrir ahora que no se muestre, siempre debe de mostrarse ahora, solo que probablemente no del primer intento... Dime que notas, para saber si puedo hacer algo más.

Saludos.

**Comment by lestcape** [comment]
Este problema yo suponía iba a pasar. El asunto es que gtk requiere (por asuntos de memoria, para no gastar memoria por gusto), que yo mande a cerrar la conección del menu las mismas veces que la mando a abrir, pero en un reinicio de cinnamon, todos mis objetos se destruyen y pierdo la cuenta que llevaba, por lo que informo mal y esto hace que las aplicaciones de gtk se cierren (lo cual no es gracioso, pierdes tu trabajo). Para resolver esto, lo que hice es que cada vez que pido algo cierro la conección seguido de eso, y bueno, con la conección cerrada no me entero de ningun cambio. Ofice manda el menu sin nada cuando arranca y luego lo actualiza. Yo leo y no encuentro nada, pero no me entero de la actualización despues. Lo que hice es que mando a actualizar cada vez que el menu se muestra (sea necesario o no lo se). Esto no quiere decir entonces que el problema se resuelva, solo quiere decir que hay mas chances de que se muestre el menu que antes.

Resolver el problema realmente dentro de cinnamon, no creo que sea posible, pero puede ser posible, agregar cosas para que por lo menos sea más pasajero, como un tiempo de espera, para despues mostrar el menu, lo cual da mala sensación, porque es demorado, pero es preferible algo demorado que simplemente nada.

**Comment by lestcape** [comment]
Despues de los últimos cambios, no he podido reproducir el problema, por lo que lo considero solucionado. Si lo puedes reproducir, dime como, para volver a abrir el hilo.

Saludos.
